import forms from '@tailwindcss/forms';

/** Design tokens — restrained dark + gold accent (product UI) */
export default {
  darkMode: 'class',
  important: '#root',
  corePlugins: {
    container: false,
  },
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#110e07',
        surface: '#16130b',
        'on-tertiary-fixed': '#00174b',
        'surface-container-high': '#2d2a21',
        'tertiary-fixed-dim': '#b4c5ff',
        'primary-container': '#d4af37',
        'on-secondary-container': '#b6b4bb',
        'on-tertiary-container': '#254188',
        'primary-fixed-dim': '#e9c349',
        'on-error-container': '#ffdad6',
        'on-secondary': '#303035',
        'surface-container-highest': '#38342b',
        'secondary-fixed': '#e4e1e8',
        'surface-variant': '#38342b',
        'surface-bright': '#3d392f',
        'on-surface': '#eae1d4',
        'secondary-fixed-dim': '#c8c5cc',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#574500',
        'on-secondary-fixed': '#1b1b20',
        'on-primary-container': '#554300',
        primary: '#f2ca50',
        'tertiary-container': '#97b0ff',
        'on-tertiary-fixed-variant': '#27438a',
        'secondary-container': '#47464c',
        tertiary: '#bfcdff',
        error: '#ffb4ab',
        destructive: '#93000a',
        'on-primary': '#3c2f00',
        'error-container': '#93000a',
        secondary: '#c8c5cc',
        'on-tertiary': '#082b72',
        'on-surface-variant': '#d0c5af',
        'on-secondary-fixed-variant': '#47464c',
        outline: '#99907c',
        'primary-fixed': '#ffe088',
        'on-background': '#eae1d4',
        'inverse-surface': '#eae1d4',
        'surface-tint': '#e9c349',
        'on-primary-fixed': '#241a00',
        'surface-container': '#231f17',
        'surface-dim': '#16130b',
        'surface-container-low': '#1f1b13',
        'inverse-primary': '#735c00',
        background: '#101012',
        /** shadcn-style semantic tokens — used by `@/components/ui/button` etc. */
        foreground: '#eae1d4',
        muted: '#231f17',
        'muted-foreground': '#99907c',
        accent: '#38342b',
        'accent-foreground': '#eae1d4',
        border: 'rgba(255, 255, 255, 0.08)',
        input: 'rgba(255, 255, 255, 0.1)',
        ring: '#f2ca50',
        'primary-foreground': '#3c2f00',
        'secondary-foreground': '#1b1b20',
        'destructive-foreground': '#ffdad6',
        'tertiary-fixed': '#dbe1ff',
        'outline-variant': '#4d4635',
        'inverse-on-surface': '#343027',
      },
      maxWidth: {
        'max-width': '1280px',
        'container-max': '1440px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        margin: '32px',
        gutter: '24px',
        base: '8px',
        'section-gap': '128px',
        'margin-page': '64px',
        unit: '8px',
      },
      fontFamily: {
        'headline-lg': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'display-xl': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'label-caps': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'hero-title': ['Outfit', '"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'hero-title': ['80px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
      },
      boxShadow: {
        'primary-glow': '0 12px 32px rgba(0, 0, 0, 0.45)',
        'gold-glow': '0 4px 20px rgba(0, 0, 0, 0.35)',
        'stitch-sm':
          '0 1px 3px rgba(0, 0, 0, 0.4), inset 0 1px 0 rgba(255, 255, 255, 0.04)',
        'stitch-md':
          '0 8px 24px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(255, 255, 255, 0.06)',
      },
      borderRadius: {
        stitch: '20px',
      },
      transitionTimingFunction: {
        stitch: 'cubic-bezier(0.2, 0, 0, 1)',
      },
      keyframes: {
        'slide-in-right': {
          '0%': { transform: 'translateX(100%)', opacity: '0.85' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
      animation: {
        'slide-in-right': 'slide-in-right 0.22s cubic-bezier(0.2, 0, 0, 1) forwards',
      },
    },
  },
  plugins: [forms],
};
